version: 1.0
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s -  %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.FileHandler
    level: INFO
    formatter: simple
    filename: features_builder.log
    #maxBytes: 1024000
loggers:
  "":
    level: INFO
    handlers: [file, console]